### ISSUE TITLE
Form appears unavailable for editing to team

### ISSUE THREAD

**Issue by magee** [ph8tel/RPT-Chrome-Extension#4]
I tried changing the title on the form from "Pairing Observations" to "Student Observations" and learned I can't access the form using its url.  Can you copy the form to the "RPT Chrome Extension" folder in our RPT Lab storage so we have access to it?

https://drive.google.com/drive/folders/1X00GCZxNeEyazcLGI7SeNm-ZsnW_rQGs

**Comment by ph8tel** [comment]
I'm not sure about that. I think I will have to rebuild the form due to a setup error on my end.  I'm trying now. 
For a workaround I manually added staff work emails as collaborators. Will work with NFD to test this ASAP but in theory, if you are signed in to google with HR account, you should be able to edit.

**Comment by ph8tel** [comment]
Getting xfer failure due to domain. Rebuilding in correct folder now. Will update extension html to new src

**Comment by ph8tel** [comment]
Form now rebuilt and data copied to https://docs.google.com/forms/d/1ttHp9YnI7s_Uw7EC7LrLuGCWfs1XtybN7RfF3dabCAs/edit
